trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: ArchiveFiles@2
  displayName: 'Archive HTML files'
  inputs:
    rootFolderOrFile: '$(Build.SourcesDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/html_project.zip'
    replaceExistingArchive: true

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/html_project.zip'
    ArtifactName: 'html_project'
    publishLocation: 'container'

# - task: AzureWebApp@1
#   displayName: 'Deploy to Azure Web App'
#   inputs:
#     azureSubscription: 'github.com_vkari'
#     appName: 'test'
#     package: '$(Build.ArtifactStagingDirectory)/html_project.zip'
