trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- script: |
    echo "Displaying some specific environment variables:"
    echo "Build Requested For: $BUILD_REQUESTEDFOR"
    echo "Chrome Binary Location: $CHROME_BIN"
    echo "Android NDK Root: $ANDROID_NDK_ROOT"
    echo "Go Root for 1.22.x: $GOROOT_1_22_X64"
    echo "System Default Working Directory: $SYSTEM_DEFAULTWORKINGDIRECTORY"
    echo "Pipeline Workspace: $PIPELINE_WORKSPACE"
  displayName: 'Show selected environment variables'

- script: |
    echo "Checking software versions:"
    echo "Go version:"
    go version
    echo "Google Chrome version:"
    google-chrome --version
    echo "Java version:"
    java -version
    df -h 
    free -h
    ls -lrt /mnt
    
  displayName: 'Check software versions'

- script: |
    echo "System architecture and other details:"
    echo "System Architecture: $AGENT_OSARCHITECTURE"
    echo "Image OS: $ImageOS"
    echo "Agent Status: $AGENT_JOBSTATUS"
    echo "Swift Path: $SWIFT_PATH"
  displayName: 'System Details'

- script: |
    echo "Current path settings:"
    echo $PATH
  displayName: 'Display PATH environment variable'

